name: CertLogic Validation
on:
  workflow_dispatch:
    inputs:
      country_code:
        description: 'Country Code'
        required: true
        default: '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x]
    steps:
     - uses: actions/checkout@v2
     - name: Install Node
       uses: actions/setup-node@v1
       with:
          node-version: '15.x'
     - name: Run tooling build script
       run:  (cd tooling ; sh build.sh)
