# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Certlogic Validation
on:
  workflow_dispatch:
    inputs:
      country_code:
        description: 'Country Code'
        required: true
        default: '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x]
    steps:
     - uses: actions/checkout@v2
     - name: Install Node
       uses: actions/setup-node@v1
       with:
          node-version: '15.x'
     - name: Clone Business Rule Repo
       run:  git clone https://github.com/ehn-dcc-development/dgc-business-rules.git
     - name: Build Certlogic JS
       run: cd 'dgc-business-rules/certlogic/certlogic-js'&& npm ci && npm run build --if-present
     - name: Build Certlogic Validation
       run: cd 'dgc-business-rules/certlogic/certlogic-validation' && npm ci && npm run build --if-present


